### ISSUE TITLE
Error Message on SPSS that robmed could not be loaded?

### ISSUE THREAD

**Issue by K-Username** [aalfons/robmed#32]
I was trying to run my analysis and keep getting a notification that robmed could not be loaded?
Any suggestion on how to fix this?
![ROBMED Error](https://user-images.githubusercontent.com/105982967/169658162-d45ed677-2c72-4abb-ba73-300607281978.png)

**Comment by aalfons** [comment]
Can you give me some more information? What version of `SPSS` are you using? What version of `R` do you have installed?

Did you follow all the steps for installing the installation bundle as described on https://github.com/aalfons/ROBMED-RSPSS?

Specifically, can you open `R` and check if package `robmed` is actually installed? I think ran into this error message once when I had forgotten to install package `robmed` after a fresh installation of `R`.

P.S.: Since you are using the package from SPSS, this should have been posted on the repository of the SPSS extension bundle. If you run into other issues with the extension bundle in the future, please post them there: https://github.com/aalfons/ROBMED-RSPSS/issues

**Comment by K-Username** [comment]
I doubled checked r and definitely had Robmed installed, but I uninstalled it from SPSS and reinstalled it, and it seems to work now.
Thank you for your help!

**Comment by aalfons** [comment]
No problem. Great that a reinstall fixed it.
