### ISSUE TITLE
How to plot the path diagram with results ?

### ISSUE THREAD

**Issue by dengxuebin** [aalfons/robmed#47]
Hi aalfons
     I found robmed was a very convenient package for mediation analysis, especially for building formula including multiple mediators. But I did not find the function to plot path diagram like following pictures .  Hope your reply, thanks a lot! 

![image](https://github.com/aalfons/robmed/assets/58458637/52cb4268-7e32-4733-b070-26c385196835)

**Comment by aalfons** [comment]
Thanks for getting in touch, I'm happy that you find my software useful. Please see function `model_diagram()` in package `robmedExtra` for drawing model diagrams. 

I'll close this issue here, and if you have any further questions about this please post it on the issues page of package `robmedExtra`: https://github.com/aalfons/robmedExtra/issues

**Comment by dengxuebin** [comment]
> Thanks for getting in touch, I'm happy that you find my software useful. Please see function `model_diagram()` in package `robmedExtra` for drawing model diagrams.
> 
> I'll close this issue here, and if you have any further questions about this please post it on the issues page of package `robmedExtra`: https://github.com/aalfons/robmedExtra/issues

Hi, aalfons
I do not find the `model_diagram()` in package `robmedExtra`  . Could you give my further answer? Thanks!
