### ISSUE TITLE
variables with high number of 0s

### ISSUE THREAD

**Issue by Joseph020304** [aalfons/robmed#48]
Hi
Congratulations for the awesom package and the companion robmedExtra.

I am conducting analysis of a wide set of variables. Some of the variables used as mediators have a large number of 0s and when running the robust analysis with those variables I get the error:

Warning: S-estimated scale == 0:  Probably exact fit; check your dataWarning: initial estim. 'init' not converged -- will be return()ed basically unchangedError in if (const(t, min(1e-08, mean(t, na.rm = TRUE)/1e+06))) { : 
  valor ausente donde TRUE/FALSE es necesario

The ols boost method works, but obvioulsy variable distribution is far from normal so I prefer not to use it. 

Since the ols still works, I was wondering whether there is a way to overcome the error with the robust method. Also, I have not found what is the maximum number of 0s allowed in a mediator variable to avoid the error. 

Thanks in advance

**Comment by aalfons** [comment]
Hi, I'm glad you like the software.

Can you be more specific? How many observations do you have and how many zeros do you have in those mediators? Do you use the mediators one at a time in different analyses, or are multiple mediators entering the model?

In general, I can provide only guesses without a reproducible example.

The computation of the robust method involves an initial subsampling step that is crucial for achieving robustness. If there is a lack of variation on such a subsample (due to too many zeros) then there is a computational issue as reported in the error message. It's impossible for me to tell if this can be overcome without a reproducible example.

Also note that although the OLS works computationally, it's unclear if it gives you a reliable answer in that case. So in that sense, the OLS just obscures the problem, whereas the robust method makes it explicit that there is a problem.
